apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: go_learning
            - name: POSTGRES_PASSWORD
              value: docker_pass
            - name: POSTGRES_USER
              value: docker
          image: go-learning-db
          imagePullPolicy: IfNotPresent
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready -U docker -d go_learning
          #   failureThreshold: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          name: go-learning-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
