# DEV ONLY!
services:
  db:
    image: go-learning-db

    container_name: go-learning-db

    restart: always

    ports:
      - 5433:5432

    build:
      context: ./db/
      dockerfile: db.Dockerfile
      target: db

    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_pass
      POSTGRES_DB: go_learning

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker -d go_learning']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: go-learning-backend

    container_name: go-learning-backend

    restart: always

    ports:
      - 8080:8080

    depends_on:
      - db

    build:
      context: ./backend/
      dockerfile: backend.Dockerfile
      target: backend

    environment:
      DATABASE_URL: postgres://docker:docker_pass@db:5432/go_learning

  frontend:
    image: go-learning-frontend

    container_name: go-learning-frontend

    restart: always

    ports:
      - 3000:3000

    depends_on:
      - backend

    build:
      context: ./frontend/
      dockerfile: frontend.Dockerfile
      target: frontend

    environment:
      PUBLIC_BACKEND_URL: http://backend:8080
