apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: PUBLIC_BACKEND_URL
              value: http://backend:8080
            - name: ORIGIN
              value: http://localhost:3000
          image: go-learning-frontend
          imagePullPolicy: IfNotPresent
          name: go-learning-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
